name: FiitMeFitness
favicon: null
layout_spectrum: 0.21858445648103952
typography_spectrum: 0.15836559934541583
title: FiitMe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#5e655e'
    - '#2bf0f6'
    - '#f5f7f2'
    - '#a1a3a0'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
